### ISSUE TITLE
C7 Missing in BOM

### ISSUE THREAD

**Issue by pfuentes69** [dymczykm/classic_ii_fpu#1]
Hello,
just to confirm that C7 is not in your BOM and that it's like the C1-C5 ones (10uF 10V), right?

**Comment by dymczykm** [comment]
@pfuentes69 
Oops, sorry, that's my fault. C7 should be indeed exactly like C1-C5 (but you are not correct with the value, it should be 100nF or a similar value). You can safely run the board without this capacitor, it should be fine too. I will correct the readme in a second.

Hope that helps!

**Comment by pfuentes69** [comment]
OK. I received today the boards from PCBWAY and I was about to make one... I think I made a copy&paste error... I put the value of C6 in my message, but I meant if it was the same than C1-C5, which you already responded. 
Txs!
